modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "unlicense"

[[mods]]
modId = "clickthrougharchitectury"
version = "${version}"
displayName = "Click Through Architectury"
authors = "0rn"
description = '''
Click through signs and item frames
'''
logoFile = "icon.png"

[[dependencies.clickthrougharchitectury]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clickthrougharchitectury]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clickthrougharchitectury]]
modId = "cloth_config"
mandatory = false
versionRange = "[9,)"
ordering = "AFTER"
side = "CLIENT"